### PR TITLE
Add Cartero as a Homebrew tap

### PR DESCRIPTION
**Pull request by SoloAntonio**

### CODE REVIEW

**Review by danirod — APPROVED** [review]
Thank you for creating a tap. Maybe in the future Cartero could be sent to Homebrew Cask central, but while the application is half baked, maybe an external tap is simpler to use.

I've reworded the message in the warning prompt, because instructions for Sequoia are completely different than for older versions of macOS. (Haven't upgraded to Sequoia yet, so I cannot predict how bad it is.)

**Comment by SoloAntonio** [comment]
Thank you, Dani, for making Cartero. I’d like to publish Cartero in Homebrew Cask Central, but I need to sign and notarize the app first. I haven’t done this before, but I’m researching how to.

**Comment by danirod** [comment]
That has to be done on my side, since I'm the publisher.

I need an Apple Developer Account and notarize my application with my signature. This is still something to do, because it requires to pay a subscription. I don't know why I keep waiting for it, since it has to be done anyway, so the sooner I do this and sign my application, the better for everyone.

I don't know if it's mandatory to notarize apps in order to use third party taps.

If you want to merge the PR, you can open it again; otherwise I'll respect the decision to keep it closed.

**Comment by SoloAntonio** [comment]
This is my first PR, and since it hasn’t been merged, I assume you don’t want to merge it. However, I reopened it in case you’re still interested in merging it.

By the way, taps don’t need to be signed or notarized. I tested the tap, and it only requires the usual steps to open an unsigned app on macOS.

**Comment by danirod** [comment]
Yeah, no worries, sorry, I've been quite busy last week and I forgot to deal with the PR.

Merging this, I'm sure someone out there will find the tap useful.

Hopefully I can deal with the notarizing step soon so that it is easy to run the app.

**Pull request merged**
